### ISSUE TITLE
No redirect

### ISSUE THREAD

**Issue by davodego** [arelange/owncloud-files-hubic#4]
The button in Owncloud Adminpage don't redirect to hubic.com. I give my data in the form, the button was shown but on click nothing happend. Owncloud.log shows nothing. Apache2 ssl_access.log shows:
 [15/Jul/2015:09:26:56 +0200] "POST /owncloud/index.php/apps/files_hubic/ajax/hubic.php HTTP/1.1" 302 1026 "https://dienste.srvdg.de/owncloud/index.php/settings/admin" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"

Config:
Owncloud 8.1.
PHP 5.4
Debian Wheezy

**Comment by arelange** [comment]
Owncloud 8.1 is unfortunately not (yet ?) supported.

**Comment by remyj38** [comment]
It's working (tested with OC 8.1) since commit 37d7ee58ede0f81c1c7a214840317aeb9b7053a3

**Comment by davodego** [comment]
Confirmed,
I create the file route.php in ../appinfo/ as described in the commit and now it works with OC 8.1.1
Thanks a lot :)

**Comment by arelange** [comment]
Cool, thanks for the feedback !
